[target.aarch64-unknown-linux-musl]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-musl:edge"
[build]
default-target = "x86_64-unknown-linux-musl"
pre-build = [
	"apt-get update",
	"DEBIAN_FRONTEND=noninteractive apt-get install -y pip",
	"pip install cmake"
]
